(* open Base *)

(* let addition_test () = Alcotest.(check bool) "1 + 1 = 2" true (1 + 1 = 2) *)
(* let tools_set = [ ("Check addition", `Quick, addition_test) ];; *)

(* Alcotest.run "Tools tests" *)
(*   [ ("Tools", tools_set) ] *)
(*   Alcotest.run "Markdown" *)
(*   [ *)
(*     ( "tokenize", *)
(*       [ *)
(*         ( "Returns a list of strings", *)
(*           `Quick, *)
(*           fun () -> Alcotest.(check bool) "" (Markdown.tokenize "hello") ); *)
(*       ] ); *)
(*   ] *)
