#!/usr/bin/env ruby

puts "16 Colors, FG:"
(30..37).each do |fg|
  puts("\033[#{fg}mNormal: #{fg}; \033[#{fg + 60}mBright: #{fg + 60}")
end

puts "\033[3m (Reset everything) \033[0m"

puts "16 Colors, BG:"

(40..47).each do |bg|
  print("\033[;#{bg}mNormal: #{bg}; \033[;#{bg + 60}mBright: #{bg + 60}")

    puts "\033[0m"
end

# note that fg and bg can be combined with \033[<fg>;<bg>m

puts "\033[3m (Reset everything) \033[0m"

puts "256 Colors:"

(0..255).each do |i|
  print("\033[38;5;#{i}m#{i.to_s.rjust(5)}")
  if (i + 1) % 16 == 0
    puts
  end
end


puts

(0..255).each do |i|
  print("\033[48;5;#{i}m#{i.to_s.rjust(5)}")
  if (i + 1) % 16 == 0
    puts "\033[0m"
  end
end

puts
