#!/usr/bin/env python
import random
from pathlib import Path


def pick(items):
    return random.choice(items).strip()


with open(Path("~/.config/scripts/words_alpha.txt").expanduser()) as file:
    words = file.readlines()
    print(".".join(["testing", pick(words), pick(words), pick(words)]))
