#!/bin/bash

git checkout $TRUNKBRANCHNAME
sleep 1
git pull
sleep 1
yarn
sleep 1
yarn next lint 2> ~/lint_master.txt
sleep 1
git checkout -
yarn
sleep 1
yarn next lint 2> ~/lint_other.txt
sleep 1

nvim -c "edit ~/lint_other.txt | vsplit ~/lint_master.txt | silent windo %s/\d\+/xx/eg | windo w | windo diffthis"
