#!/usr/bin/env ruby
# frozen_string_literal: true

timelapse_root_path = File.join(Dir.home, 'Timelapse')

day = ARGV[0] || Time.now.strftime('%Y-%m-%d')

images_path = File.join(timelapse_root_path, day, '%5d.jpg')

time = Time.now.strftime('%H-%M-%S')
out_path = File.join(timelapse_root_path, "#{day}--#{time}.mov")

system "ffmpeg -y -framerate 15 -i #{images_path} " \
       "-vf \"format=yuv420p\" -vcodec libx265 -preset veryslow -crf 35 #{out_path}"

# command: List[str] = ["ffmpeg", "-y",
#                              "-framerate", "30",
#                              "-i", self.input,
#                              "-vf", "format=yuv420p",
#                              "-vcodec", "h264",
#                              self.output]
