#!/usr/bin/env ruby
# frozen_string_literal: true

timelapse_root_path = File.join(Dir.home, 'Timelapse')

day = ARGV[0] || Time.now.strftime('%Y-%m-%d')

images_path = File.join(timelapse_root_path, day, '%5d.png')

time = Time.now.strftime('%H-%M-%S')
out_path = File.join(timelapse_root_path, "#{day}--#{time}.mov")

command = "ffmpeg -y -framerate 15 -i #{images_path} -vcodec hevc_videotoolbox -q:v 65 -vf \"scale=1800:1124:force_original_aspect_ratio=decrease,pad=1800:1124:(ow-iw)/2:(oh-ih)/2:black,format=yuv420p\" #{out_path}"

puts "Command: »#{command}»"
exit 1 unless system command

